# Generated by Django 3.2 on 2024-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mpaa', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_count', models.FloatField(blank=True, null=True)),
                ('critic', models.CharField(blank=True, max_length=255, null=True)),
                ('critic_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing', models.CharField(blank=True, max_length=100, null=True)),
                ('worldwide_gross', models.CharField(blank=True, max_length=100, null=True)),
                ('russian_gross', models.CharField(blank=True, max_length=100, null=True)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
